CREATE database FBS;
 use fbs;

CREATE TABLE flight_details ( flight_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, FK1_source_details_ID INT NOT NULL, FK2_destination_airport_ID INT NOT NULL, FK3_calender INT NOT NULL, FOREIGN KEY (FK1_source_details_ID) REFERENCES Airport (id), FOREIGN KEY (FK2_destination_airport_ID) REFERENCES flight_details (flight_id), FOREIGN KEY (FK3_calender) REFERENCES Calender (id_day_date) );

CREATE TABLE Airport ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Airportname VARCHAR(255) NOT NULL, Airportlocation VARCHAR(255) NOT NULL, AirportCountry VARCHAR(255) NOT NULL, FK_flight_names INT NOT NULL, FOREIGN KEY (FK_flight_names) REFERENCES Flight_Names (flight_name_id) ); use fbs;

CREATE TABLE Seat_Details ( Seat_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, FK1_travel_class_ID INT NOT NULL, FK2_flight_ID INT NOT NULL, FOREIGN KEY (FK1_travel_class_ID) REFERENCES Travel_Class (travel_ID), FOREIGN KEY (FK2_flight_ID) REFERENCES flight_details (flight_id) ); use fbs;

CREATE TABLE Travel_Class ( travel_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, travel_class_name VARCHAR(255) NOT NULL, travel_class_capacity INT NOT NULL ); use fbs;

CREATE TABLE Flight_Cost ( PK_FK1_Seat_ID_valid_from_date INT NOT NULL, PK_FK2_seat_id INT NOT NULL, FK3_valid_to_date INT NOT NULL, FOREIGN KEY (PK_FK1_Seat_ID_valid_from_date) REFERENCES Seat_Details (Seat_id), FOREIGN KEY (PK_FK2_seat_id) REFERENCES Flight_Cost, FOREIGN KEY (FK3_valid_to_date) REFERENCES Flight_Cost ); use fbs;

CREATE TABLE Calender ( id_day_date DATE NOT NULL PRIMARY KEY, FLIGHT_DATES DATE NOT NULL, DEST VARCHAR(255) NOT NULL, BOARDED VARCHAR(255) NOT NULL ); use fbs;

CREATE TABLE Passenger ( Passenger_id INT NOT NULL PRIMARY KEY, P_firstname VARCHAR(255) NOT NULL, P_lastname VARCHAR(255) NOT NULL, P_email INT NOT NULL, P_Phonenumber INT NOT NULL, P_address INT NOT NULL, P_city VARCHAR(255) NOT NULL, P_zipcode INT NOT NULL, P_state VARCHAR(255) NOT NULL, P_country VARCHAR(255) NOT NULL ); use fbs;

CREATE TABLE Reservation ( reservation_id INT NOT NULL PRIMARY KEY, FK1_Passenger_id INT NOT NULL, FK2_Seat_id INT NOT NULL, FK3_PassengerN_id INT NOT NULL, FOREIGN KEY (FK1_Passenger_id) REFERENCES Passenger (Passenger_id), FOREIGN KEY (FK2_Seat_id) REFERENCES Seat_Details (Seat_id), FOREIGN KEY (FK3_PassengerN_id) REFERENCES Passenger ); use fbs;

CREATE TABLE Payment_Status ( Payment_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Payment INT NOT NULL, FK1_Reservation_id INT NOT NULL, FOREIGN KEY (FK1_Reservation_id) REFERENCES Reservation (reservation_id) ); use fbs;

CREATE TABLE Passenger_2 ( Passenger2_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, P_firstname VARCHAR(255) NOT NULL, P_lastname VARCHAR(255) NOT NULL, P_email INT NOT NULL, P_Phonenumber INT NOT NULL, P_address INT NOT NULL, P_city VARCHAR(255) NOT NULL, P_zipcode INT NOT NULL, P_state VARCHAR(255) NOT NULL, P_country VARCHAR(255) NOT NULL ); use fbs;

CREATE TABLE Passenger_n ( Passenger_N_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, P_firstname VARCHAR(255) NOT NULL, P_lastname VARCHAR(255) NOT NULL, P_email INT NOT NULL, P_Phonenumber INT NOT NULL, P_address INT NOT NULL, P_city VARCHAR(255) NOT NULL, P_zipcode INT NOT NULL, P_state VARCHAR(255) NOT NULL, P_country VARCHAR(255) NOT NULL ); use fbs;

CREATE TABLE Flight_Names ( flight_name_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Air VARCHAR(255) NOT NULL, AIX VARCHAR(255) NOT NULL, Akasa VARCHAR(255) NOT NULL, Go VARCHAR(255) NOT NULL, SpiceJet VARCHAR(255) NOT NULL, Vistara VARCHAR(255) NOT NULL );
INSERT INTO fbs.airport (Airportname, Airportlocation, AirportCountry, FK_flight_names) VALUES ('Maharana Pratap	Udaipur	India	Air India', 'Udaipur', "India" , "Air India"); ('Indira Gandhi International Airport', 'Delhi', "India" , "Go First"); ('Chhatrapati Shivaji Maharaj International Airport', 'Mumbia', "India" , "Akash"); ('Kempegowda International Airport', 'Bengaluru', "India" , "Vistara"); ('Toronto Pearson International Airport', 'Canada', "canada" , "Air Canada"); ('John F. Kennedy International Airport', 'New York', 'United States', 'Delta Airlines'), ('Los Angeles International Airport', 'Los Angeles', 'United States', 'American Airlines'), ('Heathrow Airport', 'London', 'United Kingdom', 'British Airways'), ('Charles de Gaulle Airport', 'Paris', 'France', 'Air France'), ('Sydney Kingsford Smith International Airport', 'Sydney', 'Australia', 'Qantas'), ('Beijing Capital International Airport', 'Beijing', 'China', 'Air China'), ('Dubai International Airport', 'Dubai', 'United Arab Emirates', 'Emirates'), ('Tokyo Haneda Airport', 'Tokyo', 'Japan', 'Japan Airlines'), ('Frankfurt Airport', 'Frankfurt', 'Germany', 'Lufthansa'), ('Hong Kong International Airport', 'Hong Kong', 'Hong Kong', 'Cathay Pacific'), ('Singapore Changi Airport', 'Singapore', 'Singapore', 'Singapore Airlines'), ('Toronto Pearson International Airport', 'Toronto', 'Canada', 'Air Canada'), ('Sydney Kingsford Smith International Airport', 'Sydney', 'Australia', 'Qantas'); ('Netaji Subhas Chandra Bose International Airport', 'Kolkata', 'India', 'IndiGo'), ('Cochin International Airport', 'Kochi', 'India', 'Air Asia India'), ('Sardar Vallabhbhai Patel International Airport', 'Ahmedabad', 'India', 'Air India'), ('Goa International Airport', 'Goa', 'India', 'Go First'), ('Pune Airport', 'Pune', 'India', 'Akash'), ('Jaipur International Airport', 'Jaipur', 'India', 'Vistara'), ('Lucknow Airport', 'Lucknow', 'India', 'SpiceJet'), ('Trivandrum International Airport', 'Thiruvananthapuram', 'India', 'IndiGo'), ('Biju Patnaik International Airport', 'Bhubaneswar', 'India', 'Air Asia India'), ('Coimbatore International Airport', 'Coimbatore', 'India', 'Air India'), ('Dr. Babasaheb Ambedkar International Airport', 'Nagpur', 'India', 'Go First'), ('Gaya Airport', 'Gaya', 'India', 'Akash'), ('Rajahmundry Airport', 'Rajahmundry', 'India', 'Vistara'), ('Jammu Airport', 'Jammu', 'India', 'SpiceJet');